{"stats": {"errors": 0, "failures": 5, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 5}, "results": [{"classname": "index_test:TestPythonFunctionsWithArguments", "name": "test_high_rating_func", "time": 0.0004813671112060547, "type": "failure", "errtype": "builtins.AssertionError", "message": "None != True", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 67, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 625, in run\n    testMethod()\n  File \"/home/jeetds1994/function-arguments-lab-data-science-alpha/test/index_test.py\", line 24, in test_high_rating_func\n    self.assertEqual(high_rating(fork_fig, 4), True)\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 836, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 829, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: None != True\n"}, {"classname": "index_test:TestPythonFunctionsWithArguments", "name": "test_is_better_func", "time": 0.00031495094299316406, "type": "failure", "errtype": "builtins.AssertionError", "message": "None != False", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 67, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 625, in run\n    testMethod()\n  File \"/home/jeetds1994/function-arguments-lab-data-science-alpha/test/index_test.py\", line 14, in test_is_better_func\n    self.assertEqual(is_better(frontier_restaurant, fork_fig), False)\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 836, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 829, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: None != False\n"}, {"classname": "index_test:TestPythonFunctionsWithArguments", "name": "test_is_cheaper_func", "time": 0.00016689300537109375, "type": "failure", "errtype": "builtins.AssertionError", "message": "None != True", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 67, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 625, in run\n    testMethod()\n  File \"/home/jeetds1994/function-arguments-lab-data-science-alpha/test/index_test.py\", line 19, in test_is_cheaper_func\n    self.assertEqual(is_cheaper(frontier_restaurant, fork_fig), True)\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 836, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 829, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: None != True\n"}, {"classname": "index_test:TestPythonFunctionsWithArguments", "name": "test_restaurant_name_func", "time": 0.0001728534698486328, "type": "failure", "errtype": "builtins.AssertionError", "message": "None != 'Fork & Fig'", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 67, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 625, in run\n    testMethod()\n  File \"/home/jeetds1994/function-arguments-lab-data-science-alpha/test/index_test.py\", line 6, in test_restaurant_name_func\n    self.assertEqual(restaurant_name(fork_fig), 'Fork & Fig')\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 836, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 829, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: None != 'Fork & Fig'\n"}, {"classname": "index_test:TestPythonFunctionsWithArguments", "name": "test_restaurant_rating_func", "time": 0.00018739700317382812, "type": "failure", "errtype": "builtins.AssertionError", "message": "None != 4.5", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 67, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 625, in run\n    testMethod()\n  File \"/home/jeetds1994/function-arguments-lab-data-science-alpha/test/index_test.py\", line 10, in test_restaurant_rating_func\n    self.assertEqual(restaurant_rating(fork_fig), 4.5)\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 836, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 829, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: None != 4.5\n"}]}